CREATE TABLE IF NOT EXISTS lempis_cierres_diarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tenant_id INT NOT NULL,
    branch_id INT NULL,
    warehouse_id INT NULL,
    user_id INT NULL,
    closure_date DATE NOT NULL,
    opening_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    cash_sales_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    transfer_sales_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    card_sales_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    credit_sales_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    receivable_cash_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    receivable_transfer_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    receivable_card_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    expenses_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    expected_cash_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    actual_cash_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    delivered_cash_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    variance_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    notes TEXT NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    INDEX ix_lempis_cierres_tenant_date (tenant_id, closure_date),
    INDEX ix_lempis_cierres_branch (branch_id),
    INDEX ix_lempis_cierres_warehouse (warehouse_id),
    CONSTRAINT fk_cierres_tenant FOREIGN KEY (tenant_id) REFERENCES lempis_empresas(id) ON DELETE CASCADE,
    CONSTRAINT fk_cierres_branch FOREIGN KEY (branch_id) REFERENCES lempis_sedes(id) ON DELETE SET NULL,
    CONSTRAINT fk_cierres_warehouse FOREIGN KEY (warehouse_id) REFERENCES lempis_bodegas(id) ON DELETE SET NULL,
    CONSTRAINT fk_cierres_user FOREIGN KEY (user_id) REFERENCES lempis_usuarios(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS lempis_gastos_caja (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tenant_id INT NOT NULL,
    closure_id INT NULL,
    branch_id INT NULL,
    user_id INT NULL,
    expense_date DATETIME NOT NULL,
    category VARCHAR(80) NOT NULL DEFAULT 'General',
    description VARCHAR(180) NOT NULL,
    payment_method ENUM('efectivo','transferencia','tarjeta','otro') NOT NULL DEFAULT 'efectivo',
    amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    notes TEXT NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    INDEX ix_lempis_gastos_tenant_date (tenant_id, expense_date),
    INDEX ix_lempis_gastos_closure (closure_id),
    INDEX ix_lempis_gastos_branch (branch_id),
    CONSTRAINT fk_gastos_tenant FOREIGN KEY (tenant_id) REFERENCES lempis_empresas(id) ON DELETE CASCADE,
    CONSTRAINT fk_gastos_closure FOREIGN KEY (closure_id) REFERENCES lempis_cierres_diarios(id) ON DELETE SET NULL,
    CONSTRAINT fk_gastos_branch FOREIGN KEY (branch_id) REFERENCES lempis_sedes(id) ON DELETE SET NULL,
    CONSTRAINT fk_gastos_user FOREIGN KEY (user_id) REFERENCES lempis_usuarios(id) ON DELETE SET NULL
);
